### ISSUE TITLE
VIDEOCART-10 Maze does not load/can't start

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/ChannelF_MiSTer#2]
Maze does not fully load and game cannot be started.  Attempted to play this via multiple different romsets and always the same result- the maze partially loads in and stops after the bottom and left portion of the outer edge.
![untitled](https://user-images.githubusercontent.com/40709481/144082158-1e915c60-e178-4537-b704-e11ca8d56869.JPG)

**Comment by Grabulosaure** [comment]
This game needs additional RAM.

Fix pushed.

**Comment by M-Walrus** [comment]
Confirmed fixed. Closing
