### ISSUE TITLE
VIDEOCART-3 Video Blackjack will not start

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/ChannelF_MiSTer#4]
Game freezes and is unresponsive after the playfield loads.  Per the instructions, after pressing button 1 to start the game, the player should be able to press button 2 (mode) to select how many players, and a "M?" should appear on the screen.  This never happens and there is no apparent way to begin the game at this point.
![untitled](https://user-images.githubusercontent.com/40709481/144084168-b02c5b87-cd9a-460b-909b-74767e4194de.JPG)

**Comment by Grabulosaure** [comment]
Fixed.

**Comment by M-Walrus** [comment]
Confirmed! thank you & happy holidays
