### ISSUE TITLE
VIDEOCART-1 Tic-Tac-Toe will not start

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/ChannelF_MiSTer#5]
Following the instructions in the manual I cannot get this game to start. After selecting 1 to start Tic-Tac-Toe, the cursor to select a square never appears and the game seems frozen with no way to start.

**Comment by Grabulosaure** [comment]
Fix pushed.

**Comment by M-Walrus** [comment]
Confirmed fixed. Closing
